### ISSUE TITLE
Multiple skos:notations

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/GDP-vocabs#9]
http://business.data.gov.uk/companies/sources/vocab/sic-2007.ttl has multiple (different)`skos:notation` statements, which is [fine as SKOS doesn't restrict this](https://www.w3.org/TR/2009/REC-skos-reference-20090818/#L2637). However, there is a [PMD4 integrity constraints that requires only one notation](https://github.com/Swirrl/pmd-rdf-validations/blob/master/pmd4/src/swirrl/validations/pmd4/SELECT_ConceptMaxOneNotation.sparql), and this is causing pipelines to fail, e.g https://ci.floop.org.uk/job/GSS_data/job/Trade/job/ONS-UK-trade-in-services-by-business-characteristics/lastCompletedBuild/testReport/(root)/pmd4_concept-schemes_SELECT_ConceptMaxOneNotation/Concept_Max_One_Notation/

**Comment by ajtucker** [comment]
Blocks GSS-Cogs/family-trade#89

**Comment by ajtucker** [comment]
Short term: can we add a (de)augmentation to remove multiple skos:notations, leaving just the one per concept?

Longer term: we don't want to be managing third party reference data to this extent and the third parties are within their right ignore any proposals to change/upstream our requests and to say that their reference data is valid wrt. the spec. We need to follow the https://en.wikipedia.org/wiki/Robustness_principle and PMD should be more accepting and allow configuration on the client side as to which notation to choose for a given concept scheme.

**Comment by Robsteranium** [comment]
I'm not quite sure what the purpose of that PMD4 constraint is, but I'd guess it relates to concept-scheme browsing. I believe it's just what the view is expecting and we could change that to handle multiple notations. I don't think there's any functionality (like filters) that would warrant further consideration. Perhaps @RicSwirrl or @RickMoynihan will know more?

SKOS does suggest that the notations ought be distinguished by datatype, which they're not here. Indeed we couldn't allow the client to choose a notation system, as you suggest, without being able to identify the codes within it (and a regex is no substitute for a datatype!).

I'd also argue that the having the `sic:condensedNotation` repeated in the `skos:notation` isn't particularly helpful because it only applies to a subset of codes anyway. It'd perhaps be better just to use the `sic:sicNotation` for the `skos:notation` since that looks to have comprehensive coverage.

**Comment by ajtucker** [comment]
One reason for the constraint IIRC was that it's hard to know how to present the CSV(W) from PMD when there's a choice of notation.

What I meant by following the robustness principle is that I think PMD should be more accepting of this data since as far as the original publisher is concerned, it's valid, and then either giving the users the choice of what notation to use, or potentially having some configuration/annotation somewhere to say which notations are the right ones.

I agree with you about the use of datatypes. This is something we could take up with the schema publisher and it would help us distinguish between the different notations.

**Comment by ajtucker** [comment]
An offending concept definition from http://business.data.gov.uk/companies/sources/vocab/sic-2007.ttl looks like this:

```
sic:10612  a                   sic:CodePoint , skos:Concept , sic:SubClass ;
        rdfs:isDefinedBy       <http://business.data.gov.uk/companies/sources/vocab/sic-2007.ttl> ;
        sic:condensedNotation  "10612"^^xsd:string ;
        sic:sicNotation        "10.61/2"^^xsd:string ;
        skos:broader           sic:10610 ;
        skos:inScheme          sic:scheme ;
        skos:notation          "10612"^^xsd:string , "10.61/2"^^xsd:string ;
        skos:prefLabel         "Manufacture of breakfast cereals and cereals-based foods"@en .
```

We need to remove the existing `skos:notation` statements and add them back using typed literals, using a query for `sic:sicNotation` and the optional `sic:condensedNotation` statements.

We should also provide a definition for these datatypes to be used in the new `skos:notation` literals, e.g.

```
sic:Notation
    a rdfs:Datatype ;
    rdfs:comment "Standard Industrial Classification (SIC) code" ;
    owl:onDatatype xsd:String ;
    owl:withRestrictions ([
            xsd:pattern "[0-9]{2}(\.[0-9]{1,2}(/[0-9])?)?|[A-U]"
        ]
    ) .
```

and then use these types, e.g.:
```
sic:10612  a                   sic:CodePoint , skos:Concept , sic:SubClass ;
        rdfs:isDefinedBy       <http://business.data.gov.uk/companies/sources/vocab/sic-2007.ttl> ;
        sic:condensedNotation  "10612"^^xsd:string ;
        sic:sicNotation        "10.61/2"^^xsd:string ;
        skos:broader           sic:10610 ;
        skos:inScheme          sic:scheme ;
        skos:notation          "10612"^^sic:CondensedNotation , "10.61/2"^^sic:Notation ;
        skos:prefLabel         "Manufacture of breakfast cereals and cereals-based foods"@en .
```

**Comment by RickMoynihan** [comment]
At the minute I think the filter bank etc is hard coded to display a `skos:notation` if there is one.  We can certainly change the code, and I suggest we do, to adjust the constraint and way this works.

However I’d much prefer to identify notations from different schemes with different predicates (though by all means feel free to add a datatype-uri too).  

Datatype URIs are unindexed, and you need to filter for them.  This means it's hard to support many useful features without long page load times.  For example, it would be nice for dataset downloads to potentially provide users with tables of observations keyed against their choice of notation, uri or label.  Finding the distinct notation schemes in use meeting an arbitrary filter criteria in order to present that choice will likely be a _very slow_ operation on large cubes or filtered slices, if we can't use an index (i.e. a predicate).

Given that you're having to munge the data to provide datatypes anyway, I'd suggest just subpropertying `skos:notation` and providing distinct properties is a better approach.

I’m also happy to adjust the constraint to accomodate a different design; but the constraint should still essentially enforce “only one notation per system of notation”.

Regarding supporting anything that is valid SKOS, I'm not sure why that is a requirement.  We are targeting an application profile, that requires stricter notions of validity.  For example codelists shouldn't ever be cyclic graphs, but SKOS schemes are unconstrained and it is valid to have cycles.  However having to support cyclic codelist graphs in all UI contexts will only lead to chaos.

**Comment by Robsteranium** [comment]
If we have the two notations in `sic:condensedNotation` and `sic:sicNotation` then users already have the choice of which predicate to use. Indeed by repeating _only_ the `sic:sicNotation` in `skos:notation` we're also saying "this is the right one". There's no need for additional configuration or annotations.

I'm sympathetic to the robustness principle - certainly more so than Rick :D - but being more accepting isn't without consequence...

Generally speaking, being more tolerant of generic data makes it harder to use it for specific applications. Being stricter in what we accept actually provides a more robust foundation for building features (fewer edge cases etc) and being "conservative in what [we then] send".

[Thomson's criticism of the principle](https://www.ietf.org/archive/id/draft-iab-protocol-maintenance-04.txt) arises from the very ambiguity Postel sought to defend against. Once you start combining standards there's ever more cases to define. Indeed this is what's led us to [write an application profile](https://github.com/Swirrl/cogs-issues/issues/261) - to define the conditions under which we can combine the standards and deliver features. I suspect this inevitably leads us to a stricter subset of each standard.

For example, in this case, if we enforce a shape for concepts that includes the ConceptMaxOneNotation constraint then it's easier to write a generic transformation to yield a standard csvw download from the graph (always having a single column for a single-valued `skos:notation` cell as in [`ldf::get_codelist`](https://github.com/Swirrl/linked-data-frames/blob/master/R/pmd.r#L168-L198)) that provides a robust foundation for downstream tabular users.

If that property is instead permitted to have a higher cardinality, distinguished by datatype then we'll need to add an `skos:notation` column per datatype and generate queries (instead of having fixed ones) that rely on filters (since datatypes are unindexed) only to then pass the problem (of ambiguity/ variety) on to tabular users.

We could do this, but I don't think following the robustness principle leads us to a strictly better outcome.

**Comment by RickMoynihan** [comment]
Regarding this particular constraint, as mentioned earlier I'm happy to consider relaxing/changing it and supporting the underlying requirement properly.

Regarding the robustness principle; I am actually more sympathetic to it than you might think, but we need to mindful of its cost, but more than that _where_ and _when_ and it is applied, and by _whom_.

Currently when we say that PMD needs to apply the robustness principle, the only meaningful place / easy place to apply it in the context of the ONS/IDP project is on demand at query time, which is IMHO usually far too late.  I'm an advocate of systems thinking here, and the best place to resolve most data quality issues isn't in the view, but usually earlier than that.

In the current ONS/IDP deployments we publish just the triples we are given, and have little control over the ingestion process.  In other deployments, e.g. for Scotland we have a tighter control over the ingestion process, so we can take on more responsibility regarding the robustness principle, because we have the ability to fix problems earlier.  

I hope that as we move towards more intentful write APIs and tooling in IDP we can be more liberal in our interpretation of inputs, and check, coerce and translate anomalies into the expected application profile more easily.  Ingestion strikes me as being the best place to resolve the bulk of these problems.

**Comment by Robsteranium** [comment]
That's a good point Rick - being "accepting" of this from the upstream data doesn't mean that we need to load it verbatim.

**Comment by ajtucker** [comment]
> That's a good point Rick - being "accepting" of this from the upstream data doesn't mean that we need to load it verbatim.

Can we move the PMD requirements discussion to Swirrl/cogs-issues#271 ?

**Comment by Robsteranium** [comment]
> Can we move the PMD requirements discussion to Swirrl/cogs-issues#271 ?

I was actually using the royal "we" as in "IDP/ COGS can accept the original without needing to load it verbatim".

Indeed I'm [proposing an alternate model](https://github.com/GSS-Cogs/GDP-vocabs/issues/9#issuecomment-867556594) instead of having [two notations distinguished by datatype](https://github.com/GSS-Cogs/GDP-vocabs/issues/9#issuecomment-866152667) that would obviate the need for new PMD requirements.

Concretely:

```turtle
sic:10612
  sic:condensedNotation "10612"^^xsd:string ; # or ^^sic:CondensedNotation
  sic:sicNotation "10.61/2"^^xsd:string ; # or ^^sic:Notation
  skos:notation "10.61/2"^^xsd:string ; # or ^^sic:Notation
```

This keeps both notations and says which is "the right one" without the need for us or downstream users to handle multiple cases or have any further configuration/ syntax.

This would work with or without custom datatypes.

**Comment by ajtucker** [comment]
In order to get past this for now, following @robons's augmentation/filter pattern, I've added a simple SPARQL update processing step and applied the following:

```
PREFIX sic:   <http://business.data.gov.uk/companies/def/sic-2007/>
PREFIX skos:  <http://www.w3.org/2004/02/skos/core#>

DELETE {
    ?c skos:notation ?n
} where {
    ?c sic:condensedNotation ?n
}
```

The idea is that this kind of fix could be applied on PMD rather than during pre-processing and will probably be more performant. We do need to track the changes we make to upstream sources and where possible move the responsibility back upstream too.
